Adding documentation on logos and MIDs
hackclub/yellow_pages pull request #31
Opened 2024-12-19 22:25 UTC by leowilkin

@Luke-Oldenburg also contributed to this one, alas live server!

Added a step by step guide for how to add logos, find merchant IDs, and contribute both to the repo.

2024-12-20 14:09 UTC, Luke-Oldenburg commented
@leowilkin we never provided details on how to make the svg.

2024-12-20 17:16 UTC, leowilkin commented
@Luke-Oldenburg oh yeah true, I think we just need to say square though. People should probs be able to work it out themselves.

2024-12-20 17:54 UTC, Luke-Oldenburg commented
Probs should have more: shape, size, color, etc.

2025-05-05 19:42 UTC, garyhtou requested changes
Let's add a section about Merchants of Records. MoRs will share its merchant ID with multiple vendors. For example, Square will show up as the merchant for many small shops. With our current setup, we don't want to include these in the yaml file, so let's add a section about that in this doc.

2025-05-05 19:42 UTC, garyhtou commented on README.md
> +1. Make your SVG of the vendor, make sure this is viewable on a white and black background so it's accessible. Your SVG should be square and black with a transparent background.
```suggestion
1. Find an existing SVG of the vendor's logo (or create one if not found), make sure this is viewable on a white and black background so it's accessible. Your SVG should be square and black with a transparent background.
```

2025-05-05 19:42 UTC, garyhtou commented on README.md
> +2. Once you have the Merchant ID, fork and open [merchants.yaml](https://github.com/hackclub/yellow_pages/blob/main/lib/yellow_pages/merchants.yaml), and at the bottom of the file add your informatio
```suggestion
2. Once you have the Merchant ID, fork and open [merchants.yaml](https://github.com/hackclub/yellow_pages/blob/main/lib/yellow_pages/merchants.yaml), and at the bottom of the file add your information in this format:
```

2025-07-31 20:47 UTC, davidcornu approved these changes

2026-04-21 05:21 UTC, merged